# This is our client-side monitoring configuration file for docker-compose
version: "3.9"

services:
  node-exporter:
    image: prom/node-exporter:v1.4.0
    restart: always
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - monitor

  promtail:
    image: grafana/promtail:3.2.1
    restart: always
    container_name: promtail
    volumes:
      - /opt/container/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - /var/log:/var/log:ro
      - /opt/container/promtail/positions.yaml:/var/lib/promtail/positions.yaml
    command:
      - "--config.file=/etc/promtail/promtail-config.yaml"
    networks:
      - monitor

networks:
  monitor:
    external: true
