server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://43.205.119.100:3100/loki/api/v1/push  # Replace with the central Loki server's IP

positions:
  filename: /etc/promtail/positions.yaml

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - 43.205.119.100
        labels:
          job: server_logs
          server: Prometheus  # Replace with the server's name
          environment: MONITORING  # Example: tag by environment
          __path__: /var/log/*.log     # Logs to be collected (you can change this path as needed)
