server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://13.229.79.31:3100/loki/api/v1/push  # Replace with the central Loki server's IP

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - 13.229.79.31
    labels:
      job: varlogs
      # server: Prometheus  # Replace with the server's name
      # environment: MONITORING  # Example: tag by environment
      __path__: /var/log/*log
      host: ${HOSTNAME}

- job_name: containers
  static_configs:
  - targets:
      - 13.229.79.31
    labels:
      job: containerlogs
      # server: Prometheus  # Replace with the server's name
      # environment: MONITORING  # Example: tag by environment
      __path__: /var/lib/docker/containers/*/*.log
      host: ${HOSTNAME}
